# Site
title:              Nico Riedmann
bio:                Software Engineer interested in smart systems and the interactions between smart people needed to create them
reading_time:       true
words_per_minute:   200
logo:               'assets/img/me_bw-circle.png'
background:         'assets/img/intro-bg.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://riedmann.dev

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed


# Social
email: nico@riedmann.dev
github-url:         UnseenWizzard
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:          nicola-michel-henry-riedmann
web: https://www.linkedin.com/in/nicola-michel-henry-riedmann/


# Gems
plugins:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
