url: https://riedmann.dev
baseurl: ""

# Site Settings
title: Nico Riedmann
email: nico@riedmann.dev
author: Nico Riedmann
description:  "I'm a Software Engineer interested in smart systems and the interactions between smart people needed to create them. This page is to collect my thoughts and things I find interesting."
keywords: "riedmann, software, cv, blog"

# custom settings
career-img: "img/timeline/default.jpg"
cv-path: "/assets/cv_nriedmann.pdf"
cv-style: davewhipp

# markdown settings
markdown: kramdown
highligher: rouge

kramdown:
  syntax_highlighter: rouge

exclude: ["Rakefile", "LICENSE", "readme.markdown", "dockerServer.sh"]
