# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nico Riedmann
email: nico@riedmann.dev
description:  "I'm a software architect at a company developing software for autonomous logistics vehicles. 
I'm interested in Robotics, AI, ML, Software Architecture, Clean Code, Agile, Leadership any many more things.
This page is to collect things I find interesting as well as links to private projects."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://unseenwizzard.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  UnseenWizzard

# Build settings
markdown: kramdown
