url: https://riedmann.dev
baseurl: ""

# Site Settings
title: Nico Riedmann
email: nico@riedmann.dev
description:  "I'm a software architect at a company developing software for autonomous logistics vehicles. 
I'm interested in Robotics, AI, ML, Software Architecture, Clean Code, Agile, Leadership and many more things.
This page is to collect things I find interesting as well as links to private projects."
keywords: "riedmann, software, cv, portfolio"

# Career Settings
# Default career thumbnail image.
career-img: "img/timeline/default.jpg"

exclude: ["Rakefile", "LICENSE", "readme.markdown"]
